#!/bin/bash 
 
## where does this script live?
## yes it is all needed to handle symlinks and multiple directories.
## sets the TOPLEVEL variable
SOURCE="${BASH_SOURCE[0]}"
TOPLEVEL="$( dirname "${SOURCE}" )"
while [ -h "${SOURCE}" ]
do 
  SOURCE="$(readlink "${SOURCE}")"
  [[ ${SOURCE} != /* ]] && SOURCE="${TOPLEVEL}/${SOURCE}"
  TOPLEVEL="$( cd -P "$( dirname "${SOURCE}"  )" && pwd )"
done
TOPLEVEL="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"
 
# source functions
for i in ${TOPLEVEL}/lib/*
do
  source $i
done

log_info "Build started"

# Setup all vars
source ${TOPLEVEL}/read_vars.sh

log_info "running make testdeps"
cd ${OPENSHIFT_REPO_DIR}/rt-upstream && make testdeps
log_info "make testdeps finished"

log_info "Running make install"
cd ${OPENSHIFT_REPO_DIR}/rt-upstream && make install
log_info "make install finished"

log_info "Building perl template -- perl_etc/etc/conf.d/openshift.conf"
sed -i'' "s|__OPENSHIFT_PERL_DIR__|${OPENSHIFT_PERL_DIR}|" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
sed -i'' "s|__RUNTIME_DIR__|${RUNTIME_DIR}|g" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
sed -i'' "s|__OPENSHIFT_PERL_IP__|${OPENSHIFT_PERL_IP}|" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
sed -i'' "s|__OPENSHIFT_PERL_PORT__|${OPENSHIFT_PERL_PORT}|" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
sed -i'' "s|__USER__|$(id -un)|" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
sed -i'' "s|__GROUP__|$(groups | cut -d ' ' -f 1)|" ${OPENSHIFT_REPO_DIR}/configs/perl_etc/etc/conf.d/openshift.conf
log_info "Finished perl template -- perl_etc/etc/conf.d/openshift.conf"

log_info "Build Finished"
