#!/bin/bash 
 
## where does this script live?
## yes it is all needed to handle symlinks and multiple directories.
## sets the TOPLEVEL variable
SOURCE="${BASH_SOURCE[0]}"
TOPLEVEL="$( dirname "${SOURCE}" )"
while [ -h "${SOURCE}" ]
do 
  SOURCE="$(readlink "${SOURCE}")"
  [[ ${SOURCE} != /* ]] && SOURCE="${TOPLEVEL}/${SOURCE}"
  TOPLEVEL="$( cd -P "$( dirname "${SOURCE}"  )" && pwd )"
done
TOPLEVEL="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"
 
# source functions
for i in ${TOPLEVEL}/lib/*
do
  source $i
done

log_info "Deploy started in directory $(pwd)"

# Setup all vars
source ${TOPLEVEL}/read_vars.sh

log_info "Copying new perl configs"
rsync -rav ${OPENSHIFT_REPO_DIR}/configs/perl_etc/. ${OPENSHIFT_PERL_DIR}/.
log_info "Finished copy of perl configs"

log_info "Deploy finished"
