#!/bin/bash 
 
## where does this script live?
## yes it is all needed to handle symlinks and multiple directories.
## sets the TOPLEVEL variable
SOURCE="${BASH_SOURCE[0]}"
TOPLEVEL="$( dirname "${SOURCE}" )"
while [ -h "${SOURCE}" ]
do 
  SOURCE="$(readlink "${SOURCE}")"
  [[ ${SOURCE} != /* ]] && SOURCE="${TOPLEVEL}/${SOURCE}"
  TOPLEVEL="$( cd -P "$( dirname "${SOURCE}"  )" && pwd )"
done
TOPLEVEL="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"
 
# source functions
for i in ${TOPLEVEL}/lib/*
do
  source $i
done

log_info "Post Deploy started"

# Setup all vars
source ${TOPLEVEL}/read_vars.sh

log_info "Cleaning up cpanminus"
if [ -d ${CPANMINUS_HOME}/work ]; then
	find ${CPANMINUS_HOME}/work -maxdepth 1 -type d -exec rm -rf {} \;
fi
log_info "Post Deploy finished"
