#!/bin/bash
DBTYPE=${DBTYPE:-Pg}
log_info "DBTYPE: ${DBTYPE}"
RUNTIME_DIR=${OPENSHIFT_REPO_DIR%*/repo/}
log_info "RUNTIME_DIR= ${RUNTIME_DIR}"
PREFIX=${RUNTIME_DIR}/install-root
log_info "PREFIX: ${PREFIX}"
#TODO add pg/mysql logic here
DBHOST=${OPENSHIFT_POSTGRESQL_DB_HOST}
log_info "DBHOST: ${DBHOST}"
DBNAME=${PGDATABASE}
log_info "DBNAME: ${DBNAME}"
DBDBA=${PGUSER}
log_info "DBDBA: ${DBDBA}"
DBUSER=${PGUSER}
log_info "DBUSER: ${DBUSER}"
DBPASS=${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
log_info "DBPASS: '********'"
